destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    false
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

# git-cola variables
cola_version: "1.7.2"
cola_release_date: "2011-12-05"
cola_downloads: "https://github.com/downloads/git-cola/git-cola"
cola_github: "https://github.com/git-cola/git-cola"
